FROM postgres:17-bookworm

# env vars
ENV POSTGRES_PASSWORD=root
ENV POSTGRES_USER=postgres
ENV POSTGRES_DB=travelpoint

# ports
EXPOSE 5432

# install necessary tools
RUN apt-get update && apt-get -y install git

# clone backend repo
RUN git clone -b feature/gr/deployment https://github.com/Usamafuward/travelpoint-mobile-server/ /opt/travelpoint-mobile-server

# restore db
RUN echo '#!/bin/bash\n\
pg_restore -U postgres -d travelpoint /opt/travelpoint-mobile-server/db-export.sql' > /docker-entrypoint-initdb.d/restore.sh \
&& chmod +x /docker-entrypoint-initdb.d/restore.sh

# to run
# docker run --name postgres --net tp -p 5432:5432 --rm -d gova/tp-db