FROM postgres:17-bookworm

# env vars
ENV POSTGRES_PASSWORD=root
ENV POSTGRES_USER=postgres
ENV POSTGRES_DB=travelpoint

# ports
EXPOSE 5432

# copy local db dump instead of cloning
COPY ../db-dump.sql /opt/db-dump.sql

# restore db
RUN echo '#!/bin/bash\n\
pg_restore -U postgres -d travelpoint /opt/db-dump.sql' > /docker-entrypoint-initdb.d/restore.sh \
&& chmod +x /docker-entrypoint-initdb.d/restore.sh

# to run
# docker run --name postgres --net tp -p 5432:5432 --rm -d gova/tp-db
